name: 'Flujo con docker-compose'
on: push
jobs:
  probar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Iniciar docker-compose'
        run:  docker-compose -f docker_compose.yml up
      - name: 'Listar los contenedores en ejecucionS'
        run:  docker ps -a
      - name: 'Mostrar las bitacoras de inicio'
        run:  docker logs basedatos
